folders:
  - name: "all_files"
    extensions:
      - "mod"
    folders:
      - name: "go_files"
        extensions:
          - "go"

# folders:
#   - name: "DocumentsFake"
#     recurse: True
#     extensions: 
#       - "go"
#       - "mod"
#     patterns:
#       - "READ"
#
#   - name: "Images"
#     extensions: 
#       - "jpg"
#       - "png"
#       - "gif"
#     patterns:
#       - "uti"
#
  # - name: "Videos"
  #   extensions:
  #     - "mp4"
  #     - "mkv"
  #     - "avi"
  #   patterns:
  #     - "test"
  #
  # - name: "Music"
  #   extensions:
  #     - "mp3"
  #     - "wav"
  #     - "flac"
  #   patterns:
  #     - "test2"
